version: '3'
services:
  first_app:
    container_name: simple-app
    build: .
    restart: always
    ports:
      - "8002:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/first_db
      SPRING_DATASOURCE_USERNAME: first_user
      SPRING_DATASOURCE_PASSWORD: root
    links:
      - postgres
      - redis-server
  postgres:
    container_name: simple-app-db
    image: "postgres:15"
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: first_db
      POSTGRES_USER: first_user
      POSTGRES_PASSWORD: root

  redis-server:
    hostname: redis
    container_name: simple-app-redis-db
    image: 'redis'
    ports:
      - "6380:6379"